x-localstreams-base: &localstreams-base
  image: franlerma/localstreams
  container_name: localstreams
  ports:
    - "15123:15123"
  volumes:
    - /dev/dri:/dev/dri
    - /opt/docker/volumes/localstreams/m3u:/data/m3u
    - /opt/docker/volumes/localstreams/picon:/data/picon
    - /opt/docker/volumes/localstreams/tmp:/tmp/acestream-cache
  environment:
    - ACESTREAM_PROXY_PORT=8080
    - ACESTREAM_POLL_TIME=0
    - ACESTRAM_RETRY_TOTAL=10
    - APP_LOG_LEVEL=DEBUG
  labels:
    - com.centurylinklabs.watchtower.enable=false
    - wud.watch=false
  restart: always
  stdin_open: true
  tty: true
  dns:
    - 1.1.1.1
    - 1.0.0.1
  networks:
    - media-network

x-acexy-base: &acexy-base
  image: ghcr.io/javinator9889/acexy:latest
  restart: always
  ports:
    - 8080:8080/tcp
  environment:
    ACEXY_LISTEN_ADDR: ":8080"
    ACEXY_SCHEME: "http"
    ACEXY_PORT: "6878"
    ACEXY_M3U8_STREAM_TIMEOUT: "60s"
    ACEXY_M3U8: "false"
    ACEXY_EMPTY_TIMEOUT: "60s"
    ACEXY_BUFFER_SIZE: 4MB
    ACEXY_NO_RESPONSE_TIMEOUT: "10s"
  networks:
    - media-network

x-acestream-base: &acestream-base
  container_name: acestream
  #image: martinbjeldbak/acestream-http-proxy:latest
  image: blaiseio/acelink:latest
  platform: linux/amd64
  restart: always
  volumes:
    - /opt/docker/volumes/localstreams/tmp/acestream:/home/appuser/.ACEStream

services:

  localstreams-regular:
    <<: *localstreams-base
    profiles: [ 'regular' ]
    environment:
      - ACESTREAM_PROXY_HOST=acexy-regular
    depends_on:
      - acexy-regular

  localstreams-vpn:
    <<: *localstreams-base
    profiles: [ 'vpn' ]
    environment:
      - ACESTREAM_PROXY_HOST=acexy-vpn
    depends_on:
      - acexy-vpn
      - acestream-vpn
      - gluetun

  acexy-regular:
    <<: *acexy-base
    container_name: acexy
    profiles: [ 'regular' ]
    environment:
      ACEXY_HOST: "acestream"
    links:
      - acestream-regular
    depends_on:
      - acestream-regular

  acexy-vpn:
    <<: *acexy-base
    profiles: [ 'vpn' ]
    environment:
      ACEXY_HOST: "gluetun"
    links:
      - gluetun
    depends_on:
      - gluetun

  acestream-regular:
    <<: *acestream-base
    profiles: [ 'regular' ]
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - media-network

  acestream-vpn:
    <<: *acestream-base
    profiles: [ 'vpn' ]
    # environment:
    #   - ALLOW_REMOTE_ACCESS=yes 
    #   - HTTP_PROXY=http://gluetun:8888
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    #networks:
    #  - media-network

  # warp:
  #   image: caomingjun/warp:latest
  #   container_name: warp
  #   profiles: [ 'warp']
  #   restart: always
  #   privileged: true
  #   devices:                   
  #     - /dev/net/tun:/dev/net/tun
  #   device_cgroup_rules:
  #     - 'c 10:200 rwm'
  #   ports:
  #     - "1080:1080"
  #     - "8621:8621"
  #     - "6881-6889:6881-6889"
  #   environment:
  #     - WARP_SLEEP=2
  #     # - WARP_LICENSE_KEY= # optional
  #   cap_add:
  #     - MKNOD
  #     - AUDIT_WRITE
  #     - NET_ADMIN
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   volumes:
  #     - /tmp/data:/var/lib/cloudflare-warp
  #   networks:
  #     - media-network

  gluetun:
    image: qmcgaw/gluetun
    profiles: [ 'vpn']
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "8888:8888/tcp"
      - "1080:1080"
      - "8621:8621"
      - "6881-6889:6881-6889"
    networks:
      - media-network
    environment:
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=162.159.192.1
      - VPN_ENDPOINT_PORT=2408
      - WIREGUARD_PUBLIC_KEY=bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
      - WIREGUARD_PRIVATE_KEY=6AdkYWQn9rhnIDlaXH1GSjmcCR5B3RWxSBO6QWz0uEQ=
      - WIREGUARD_ADDRESSES=172.16.0.2/32

networks:
  media-network:
    driver: bridge
