x-localstreams-base: &localstreams-base
  image: franlerma/localstreams
  container_name: localstreams
  ports:
    - "15123:15123"
  volumes:
    - /dev/dri:/dev/dri
    - /opt/docker/volumes/localstreams/m3u:/data/m3u
    - /opt/docker/volumes/localstreams/picon:/data/picon
    - /opt/docker/volumes/localstreams/tmp:/tmp/acestream-cache
  environment:
    - ACESTREAM_PROXY_PORT=8080
    - ACESTREAM_POLL_TIME=0
    - ACESTRAM_RETRY_TOTAL=10
    - APP_LOG_LEVEL=DEBUG
  labels:
    - com.centurylinklabs.watchtower.enable=false
    - wud.watch=false
  restart: always
  stdin_open: true
  tty: true
  dns:
    - 1.1.1.1
    - 1.0.0.1
  networks:
    - media-network

x-acexy-base: &acexy-base
  image: ghcr.io/javinator9889/acexy:latest
  restart: always
  ports:
    - 8080:8080/tcp
  environment:
    ACEXY_LISTEN_ADDR: ":8080"
    ACEXY_SCHEME: "http"
    ACEXY_PORT: "6878"
    ACEXY_M3U8_STREAM_TIMEOUT: "60s"
    ACEXY_M3U8: "false"
    ACEXY_EMPTY_TIMEOUT: "60s"
    ACEXY_BUFFER_SIZE: 4MB
    ACEXY_NO_RESPONSE_TIMEOUT: "10s"
  networks:
    - media-network

x-acestream-base: &acestream-base
  container_name: acestream
  image: martinbjeldbak/acestream-http-proxy:latest
  platform: linux/amd64
  restart: always
  volumes:
    - /opt/docker/volumes/localstreams/tmp/acestream:/home/appuser/.ACEStream

services:

  localstreams-regular:
    <<: *localstreams-base
    profiles: [ 'regular' ]
    environment:
      - ACESTREAM_PROXY_HOST=acexy-regular
    depends_on:
      - acexy-regular

  localstreams-warp:
    <<: *localstreams-base
    profiles: [ 'warp' ]
    environment:
      - ACESTREAM_PROXY_HOST=acexy-warp
    depends_on:
      - acexy-warp
      - acestream-warp
      - warp

  acexy-regular:
    <<: *acexy-base
    container_name: acexy
    profiles: [ 'regular' ]
    environment:
      ACEXY_HOST: "acestream"
    links:
      - acestream-regular
    depends_on:
      - acestream-regular

  acexy-warp:
    <<: *acexy-base
    profiles: [ 'warp' ]
    environment:
      ACEXY_HOST: "warp"
    links:
      - warp
    depends_on:
      - warp

  acestream-regular:
    <<: *acestream-base
    profiles: [ 'regular' ]
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - media-network

  acestream-warp:
    <<: *acestream-base
    profiles: [ 'warp' ]
    depends_on:
      - warp
    network_mode: "service:warp"

  warp:
    image: caomingjun/warp:latest
    container_name: warp
    profiles: [ 'warp']
    restart: always
    privileged: true
    devices:                   
      - /dev/net/tun:/dev/net/tun
    device_cgroup_rules:
      - 'c 10:200 rwm'
    ports:
      - "1080:1080"
      - "8621:8621"
      - "6881-6889:6881-6889"
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /tmp/data:/var/lib/cloudflare-warp
    networks:
      - media-network

networks:
  media-network:
    driver: bridge
